### ISSUE TITLE
Bug when dealing with paths in Windows

### ISSUE THREAD

**Issue by alexandernst** [RobinCK/css-aliases#1]
The `resolve` function, when running on Windows, will return an invalid HTML url path.

Say that I have an import such as `background-image: ulr('@alias/foo/bar.png')`

The resolve function will return `background-image: url('..\..\..\foo\bar.png')` (because Windows uses inverse slash and the library is using `path.relative`).

The fix is very simple. Just add `res.replace(/\\/g, '/');` add the end of the function, in the return statement.

**Comment by alexandernst** [comment]
Do you want me to make a patch @RobinCK ?

**Comment by RobinCK** [comment]
@alexandernst 
I'll be very grateful.

**Comment by RobinCK** [comment]
@alexandernst thanks

updated and published new version to npm
[gulp-style-aliases](https://www.npmjs.com/package/gulp-style-aliases)
[alias-resolve-loader](https://www.npmjs.com/package/alias-resolve-loader)
